[build]
  command = "npm install"
  functions = "functions"

[functions]
  included_files = ["functions/clash-rules.js"]

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200